### ISSUE TITLE
Question about the integration

### ISSUE THREAD

**Issue by TRexStark** [thecogworks/Cogworks.Tinifier#1]
Hi there

Thank you for this package. Tinify now provides image conversion including to WebP. Does the package support/provide that?

Thanks
Tarik.

**Comment by alfonso-jimenez-evelyn** [comment]
Hi,unfortunately the conversion to WebP is not supported yet, however it will be taken in mind for the next version.

**Comment by TRexStark** [comment]
Thanks @alfonso-jimenez-evelyn that would be awesome!
